In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/movie-dataset/Movie_Id_Titles (1).csv

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("movies.csv")

In [2]:
df=pd.read_csv("/kaggle/input/movie-dataset/Movie_Id_Titles (1).csv")

In [3]:
df.nunique()

item_id    1682
title      1664
dtype: int64

In [4]:
df.info

<bound method DataFrame.info of       item_id                                      title
0           1                           Toy Story (1995)
1           2                           GoldenEye (1995)
2           3                          Four Rooms (1995)
3           4                          Get Shorty (1995)
4           5                             Copycat (1995)
...       ...                                        ...
1677     1678                          Mat' i syn (1997)
1678     1679                           B. Monkey (1998)
1679     1680                       Sliding Doors (1998)
1680     1681                        You So Crazy (1994)
1681     1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]>

In [5]:
df.shape

(1682, 2)

In [6]:
df.describe

<bound method NDFrame.describe of       item_id                                      title
0           1                           Toy Story (1995)
1           2                           GoldenEye (1995)
2           3                          Four Rooms (1995)
3           4                          Get Shorty (1995)
4           5                             Copycat (1995)
...       ...                                        ...
1677     1678                          Mat' i syn (1997)
1678     1679                           B. Monkey (1998)
1679     1680                       Sliding Doors (1998)
1680     1681                        You So Crazy (1994)
1681     1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]>

In [7]:
df.head(4)

   item_id              title
0        1   Toy Story (1995)
1        2   GoldenEye (1995)
2        3  Four Rooms (1995)
3        4  Get Shorty (1995)

In [3]:
df.shape #rows,columns
df.columns #column names
df.info() #data type + null values
df.describe() #stats(numerical)

<class 'pandas.DataFrame'>
RangeIndex: 1682 entries, 0 to 1681
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   item_id  1682 non-null   int64
 1   title    1682 non-null   str
dtypes: int64(1), str(1)
memory usage: 26.4 KB

           item_id
count  1682.000000
mean    841.500000
std     485.695893
min       1.000000
25%     421.250000
50%     841.500000
75%    1261.750000
max    1682.000000

In [5]:
df.isnull().sum()

item_id    0
title      0
dtype: int64

In [6]:
df = df.drop_duplicates()

In [15]:
df=df[['item_id','title']]

In [16]:
df=pd.get_dummies(df, drop_first=True)

In [20]:
df=df.dropna()

In [21]:
print("total movies:", len(df))

total movies: 1682

In [26]:
df['item_id'].head(10)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: item_id, dtype: int64

In [34]:
print(df.columns)

Index(['item_id', 'title_1-900 (1994)', 'title_101 Dalmatians (1996)',
       'title_12 Angry Men (1957)', 'title_187 (1997)',
       'title_2 Days in the Valley (1996)',
       'title_20,000 Leagues Under the Sea (1954)',
       'title_2001: A Space Odyssey (1968)',
       'title_3 Ninjas: High Noon At Mega Mountain (1998)',
       'title_39 Steps, The (1935)',
       ...
       'title_Yankee Zulu (1994)', 'title_Year of the Horse (1997)',
       'title_You So Crazy (1994)', 'title_Young Frankenstein (1974)',
       'title_Young Guns (1988)', 'title_Young Guns II (1990)',
       'title_Young Poisoner's Handbook, The (1995)',
       'title_Zeus and Roxanne (1997)', 'title_unknown',
       'title_Á köldum klaka (Cold Fever) (1994)'],
      dtype='str', length=1664)